export const SAFTEYQUESTIONS = [
    "All employees have the proper PPE and are currently wearing the appropriate PPE",
     "Voltage and MAD are known and communicated",
     "The plan for the work is completely communicated with all employees",
     "Job set up, is in place to protect the crew and public",
     "Is traffic control needed",
     "Could any portion of the tree being removed or trimmed contact the lines",
     "If so, are proper measures in place to ensure the lines",
     "The emergency plan is in place, and the tree rescue has been planned",
     "First aid kits, fire extinguishers, and fire tools are on site",
     "All equipment, rigging, and ropes has been inspected",
     "Is right equiment on sight, for the right job",
     "Drop zone and observer zone have been established and are clearly marked",
     "Proper chipping operations, including loading material from the side are present",
     "Is the crew in complete communication and working safe at all times",
     "Is the job briefing written and understood",
     "Was the truck inspection done"
    ];
export const INPUTFIELDNAMES = [
    "Date",
    "Time Arrived",
    "Time departed",
    "Region",
    "SubContractor Name",
    "General Foreperson Name",
    "Member Name",
    "Member ID #",
    "Chipper ID #",
    "Member Name",
    "Member ID #",
    "Other Equipment ID #",
    "Section",
    "Zone",
    "Item #",
    "Location or Address of Site"
];
